### ISSUE TITLE
Elasticsearch 2.0 support

### ISSUE THREAD

**Issue by pmcclelland** [elasticquent/Elasticquent#11]
I have been making some changes on my fork of Elasticquent to support Elasticsearch 2.0. I am still working on it but when I am done I will put up a pull request.

**Comment by timgws** [comment]
:+1: thanks @pmcclelland

**Comment by rachellji** [comment]
Thanks @pmcclelland

**Comment by timgws** [comment]
v1.0.4 fixes this issue. :+1:

**Comment by timgws** [comment]
https://github.com/elasticquent/Elasticquent/commit/2d45d605ec3748df3f80598cd44648d172342206
