### ISSUE TITLE
LOCALHOST: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster

### ISSUE THREAD

**Issue by neamtua** [elasticquent/Elasticquent#117]
Hi,

Ran into this issues while the server was running some jobs. Worked fine up to one point until my error log got filled with the error:

> Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster

I'm not running something special, it's connecting on localhost, no passwords, nothing. Server is CentoOS 6.8.
First thing i've tried was to login to the server and simply curl http://localhost:9200. That worked. Process was up and fine.
Then I tried using php artisan tinker to try and test the actual actions that I make. The only actions I make in the code is to addToIndex and searchByQuery. They both worked. But somehow my jobs were still filling the log with this error.

Here's the full error log from where Elasticsearch actually gets in play:

> [2016-09-28 02:55:17] live.ERROR: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51
> Stack trace:
> # 0 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
> # 1 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport->getConnection()
> # 2 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(228): Elasticsearch\Transport->performRequest('PUT', '/my_custom_inde...', Array, '{"id_dosar":223...', Array)
> # 3 /home/site/new/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections{closure}(Array)
> # 4 /home/site/new/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
> # 5 /home/site/new/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
> # 6 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(283): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
> # 7 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Elasticsearch\Connections\Connection->Elasticsearch\Connections{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
> # 8 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(99): Elasticsearch\Connections\Connection->performRequest('PUT', '/my_custom_inde...', Array, '{"id_dosar":223...', Array, Object(Elasticsearch\Transport))
> # 9 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(79): Elasticsearch\Transport->performRequest('PUT', '/my_custom_inde...', Array, Array, Array)
> # 10 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(791): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
> # 11 /home/site/new/vendor/elasticquent/elasticquent/src/ElasticquentTrait.php(314): Elasticsearch\Client->index(Array)
> # 12 /home/site/new/app/Ameya/Sources/PortalJust.php(220): Topchecks\PortalJustParte->addToIndex()

The code is simply this

``` php
foreach ($inserts as $insert) {
    $parteDb = new PortalJustParte();
    $parteDb->id_dosar = $insert['id_dosar'];
    $parteDb->nume = $insert['nume'];
    $parteDb->calitate_parte = $insert['calitate_parte'];
    $parteDb->save();
    $parteDb->addToIndex();
}
```

Elastiquent config is this:

``` php
'config' => [
        'hosts'     => ['localhost:9200'],
        'retries'   => 1,
    ],
'default_index' => 'my_custom_index_name',
```

Any help would be appreciated.  Tried googling this but all connection problems were with outside servers, not localhost ones.

**Comment by timgws** [comment]
Quick question, are you using dev-master in your composer.json file?

---- On Wed, 28 Sep 2016 16:00:46 +1000 notifications@github.com wrote ----

Hi,

Ran into this issues while the server was running some jobs. Worked fine up to one point until my error log got filled with the error:

Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster

I'm not running something special, it's connecting on localhost, no passwords, nothing. Server is CentoOS 6.8.
First thing i've tried was to login to the server and simply curl http://localhost:9200. That worked. Process was up and fine.
Then I tried using php artisan tinker to try and test the actual actions that I make. The only actions I make in the code is to addToIndex and searchByQuery. They both worked. But somehow my jobs were still filling the log with this error.

Here's the full error log from where Elasticsearch actually gets in play:

[2016-09-28 02:55:17] live.ERROR: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51
Stack trace:
#0 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport->getConnection()
#2 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(228): Elasticsearch\Transport->performRequest('PUT', '/my_custom_inde...', Array, '{"id_dosar":223...', Array)
#3 /home/site/new/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections{closure}(Array)
#4 /home/site/new/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#5 /home/site/new/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#6 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(283): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#7 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Elasticsearch\Connections\Connection->Elasticsearch\Connections{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#8 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(99): Elasticsearch\Connections\Connection->performRequest('PUT', '/my_custom_inde...', Array, '{"id_dosar":223...', Array, Object(Elasticsearch\Transport))
#9 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(79): Elasticsearch\Transport->performRequest('PUT', '/my_custom_inde...', Array, Array, Array)
#10 /home/site/new/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(791): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#11 /home/site/new/vendor/elasticquent/elasticquent/src/ElasticquentTrait.php(314): Elasticsearch\Client->index(Array)
#12 /home/site/new/app/Ameya/Sources/PortalJust.php(220): Topchecks\PortalJustParte->addToIndex()

The code is simply this

foreach ($inserts as $insert) {
    $parteDb = new PortalJustParte();
    $parteDb->id_dosar = $insert['id_dosar'];
    $parteDb->nume = $insert['nume'];
    $parteDb->calitate_parte = $insert['calitate_parte'];
    $parteDb->save();
    $parteDb->addToIndex();
}
Elastiquent config is this:

'config' => [
        'hosts'     => ['localhost:9200'],
        'retries'   => 1,
    ],
'default_index' => 'my_custom_index_name',
Any help would be appreciated. Tried googling this but all connection problems were with outside servers, not localhost ones.
