### ISSUE TITLE
How to index all phones of a person into the person document?

### ISSUE THREAD

**Issue by warrio4** [elasticquent/Elasticquent#141]
Hi,

I have a model Person with a 1:N relation with a model Phone (A person can have 1 or many phones)
How is it possible to index in each person document all the phones related to it? Is it even possible?

The purpose is to search a person using his name or his phone number.

I can do it by searching each model separately, but I would like to know if it's possible to combine these two.

**Comment by a1tem** [comment]
@warrio4 have you found a solution?

**Comment by warrio4** [comment]
I used plasticsearch instead of elastiquent.
