### ISSUE TITLE
Query about project activity

### ISSUE THREAD

**Issue by lthurston** [elasticquent/Elasticquent#155]
Hi,
This project doesn't appear to have a lot of recent activity on it. I'm trying to decide if it's worth my time to try to get past ElasticSearch 6 issues with a library with 74 issues, 10 pull requests and 0 commits in the last 3 months. To be clear, this isn't a complaint or criticism, just a query: is anyone going to be actively managing or developing this project in the near future?

thanks,
Lucas

**Comment by timgws** [comment]
Yes, there will be :)
