### ISSUE TITLE
Elastic Search 

### ISSUE THREAD

**Issue by lord-zeus** [elasticquent/Elasticquent#158]
On search it only returns a max of 10 results 
can any one help out ?

**Comment by timgws** [comment]
What is the code that you are using to perform the search?

**Comment by coffeeburrito** [comment]
Returning 10 results is the default behaviour of ElasticSearch (see https://www.elastic.co/guide/en/elasticsearch/reference/6.x/search-request-from-size.html)

@lord-zeus you should specify the "size" parameter in your query
