### ISSUE TITLE
Failed to connect to localhost port 9200: Connection refused: elasticquent for Laravel 5.1

### ISSUE THREAD

**Issue by ejlocop** [elasticquent/Elasticquent#16]
i'm getting the error : Failed to connect to localhost port 9200: Connection refused. 
docs says that i need to config elasticquent.php: but this file doesn't exists in any folders.

where can i config my ports?

**Comment by timgws** [comment]
What port is Elasticsearch running on?

`elasticquent.php` should be in `app/config`. You can see the documentation here: https://github.com/elasticquent/Elasticquent#elasticsearch-configuration

Inside the array, you will see a `config` key. The value for that key is another array with the key `hosts`.  That should have the value of the Elasticsearch server that you want to connect to.

If the file does not exist, you can create it (`app/config/elasticquent.php`).
