### ISSUE TITLE
deleteMapping wrong method

### ISSUE THREAD

**Issue by maganius** [elasticquent/Elasticquent#177]
im trying use deleteMapping over Curso Model but it throw this exception:

`Incorrect HTTP method for uri [/portal/cursos/_mapping] and method [DELETE], allowed: [PUT, GET, POST]", "status":405`

`if(Curso::mappingExists()){
            Curso::deleteMapping();
        }`

**Comment by techsemicolon** [comment]
I am also having similar issue. I have dev-master of the package.

**Comment by coffeeburrito** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-delete-mapping.html

It is no longer possible to delete type mappings according to ES
documentation.

**Comment by techsemicolon** [comment]
@coffeeburrito Thanks man That makes lot of sense 👍 :)
