### ISSUE TITLE
Is there a way of storing related models with a document?

### ISSUE THREAD

**Issue by TomCaserta** [elasticquent/Elasticquent#18]
Not sure if this is directly related to this library however I am using Elasticquent to store products and index them. Each of these products also has related models such as the user that created them, the images, the locations etc. 

Is there a way using Elastiquent to store these in the same document as the product itself and possibly make them searchable? Im not sure how exactly you would go about doing this though.

**Comment by timgws** [comment]
Elasticsearch is really a flat database, it doesn't handle relationships all that well. 

Elasticsearch has an amazing guide, and one of the chapters is all about handling relationships in your data: https://www.elastic.co/guide/en/elasticsearch/guide/current/relations.html

There are two main ways that data is searched like this with ES:
* Application Joins (https://www.elastic.co/guide/en/elasticsearch/guide/current/application-joins.html), where you store the data inside Elasticsearch (eg, `product` was created by `user` 9). Once you get the results, you loop through them all and get the users with ID #9.

* Parent-Child Mapping (https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html) which is much like your JOIN inside a relational database.

**Comment by TomCaserta** [comment]
Right, I was thinking it would be like the first bullet point (like NoSQL databases) however I cannot seem to figure out a way of using this library to do exactly that. The only way I can think of is hooking to update events on the models and manually updating elasticsearch (Rather than using any of the methods this library really provides).

I suppose this would be a feature request?

**Comment by jontroncoso** [comment]
I was going to :+1: this, but then I kept reading. There actually is a way to do this using the `getIndexDocumentData` method.

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Elasticquent\ElasticquentTrait;

class Location extends Model
{
    use ElasticquentTrait;
    public function getIndexDocumentData()
    {
        return array(
            'id'        => $this->id,
            'type'      => $this->type,
            'name'      => $this->name,
            'location'  => rtrim(number_format($this->address->longitude,6), '0').','.rtrim(number_format($this->address->latitude,6), '0')
        );
    }

    protected $mappingProperties = [
        'name' => [
            'type' => 'string',
            "analyzer" => "standard",
        ],
        'type' => [
            'type' => 'string',
            'index' => 'not_analyzed'
        ],
        'location' => [
            "type" => "geo_point"
        ],
    ];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'locations';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['address_id', 'name', 'type', 'phone', 'url', 'active'];

    // relationships
    public function address()
    {
        return $this->belongsTo('App\Address');
    }
```

**Comment by TomCaserta** [comment]
Thats awesome, thanks for the example @jontroncoso!

**Comment by timgws** [comment]
Thanks @jontroncoso... is it OK if I add this to a wiki for EQ?
