### ISSUE TITLE
Question about boosted fields in Multi Match Query

### ISSUE THREAD

**Issue by tortuetorche** [elasticquent/Elasticquent#21]
Hi,

Is it possible to apply boost on Individual fields with the caret (^) notation?
Like this sample:
```json
{
  "multi_match" : {
    "query" : "this is a test",
    "fields" : [ "subject^3", "message" ] 
  }
}
```
Source: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#CO115-1

If it's possible, how to do this with your package?
Something like that?

```php
$client = new \Elasticsearch\Client();

$params = [
    'index' => 'default',
    'type'  => 'books'
    'body' => [
        'multi_match' => [
            'query' => 'Moby Dick',
            'fields' => ['title^3', 'author']
        ]
    ]
];

$collection = new \Elasticquent\ElasticquentResultCollection($client->search($params), new Book);
```
The `title` field is three times as important as the `author` field. 

See https://github.com/adamfairholm/Elasticquent/issues/25 for the original issue and https://github.com/iverberk/larasearch/issues/73 for a similar feature request on another Laravel Elastic Search package.

Cheers,
Tortue Torche

**Comment by timgws** [comment]
Did you try `complexSearch`? This should do exactly as you have described. If it does not, please let me know.

```php
    $books = Book::complexSearch([
        'body' => [
            'multi_match' => [
                'query' => 'Moby Dick',
                'fields' => ['title^3', 'author']
            ]
        ]
    ]);
```

**Comment by timgws** [comment]
Also, you could use `searchByQuery` if you do not need extra parameters...

```php
    $books = Book::searchByQuery([
        'multi_match' => [
            'query' => 'Moby Dick',
            'fields' => ['title^3', 'author']
        ]
    ]);
```

Here (https://github.com/elasticquent/Elasticquent#query-based-search) is the documentation!

**Comment by timgws** [comment]
@tortuetorche ... did this answer your question?

**Comment by tortuetorche** [comment]
Yes you did :ok_hand:
Your package will be very useful for my future projects! :sunglasses:

Many thanks :+1:
