### ISSUE TITLE
If Elasticquent is compatible with Laravel 7?

### ISSUE THREAD

**Issue by PetroGromovo** [elasticquent/Elasticquent#219]
Hello,
If Elasticquent is compatible with Laravel 7 version?
As I see, seems , no...
Could you please to upgrade Elasticquent to Laravel 7 ?

Thanks!

**Comment by hapo-vinhdq** [comment]
i can't composer update with laravel v7

**Comment by hapo-DucMinh** [comment]
so same I can't using Elasticquent with Laravel v7, pls help.

**Comment by timgws** [comment]
This is fixed in master.
