### ISSUE TITLE
support laravel v7.

### ISSUE THREAD

**Issue by hapo-vinhdq** [elasticquent/Elasticquent#220]
<img width="1408" alt="Screen Shot 2020-04-20 at 13 53 42" src="https://user-images.githubusercontent.com/46306470/79722560-7988a300-830e-11ea-97f2-d1c247b08e5a.png">

**Comment by timgws** [comment]
Thanks for the screenshot.

As per #219, this should be fixed. Try clearing your cache, and upgrade again.
