### ISSUE TITLE
Conflict with illuminate/database of Laravel 8.x

### ISSUE THREAD

**Issue by nguyenvankiem** [elasticquent/Elasticquent#230]
![image](https://user-images.githubusercontent.com/13434018/100713696-40a5c600-33e7-11eb-97ce-9d1292487486.png)

**Comment by techtic-sumit** [comment]
So this package is not longer useful for laravel 8.x.
correct...!

**Comment by criebs-cmdagency** [comment]
#237 @techtic-sumit @nguyenvankiem

**Comment by duyngha** [comment]
I think this package is using an outdated version of https://github.com/elastic/elasticsearch-php package. If you are using ES >= 6.0, it might not compatible with elasticsearch-php package. So it may be causing the errors.

**Comment by camohub** [comment]
It is long time ago. Should I use pure elasticsearch/elasticsearch-php?

**Comment by timgws** [comment]
```json
{
    "require": {
        "elasticquent/elasticquent": "dev-master"
    }
}
```

**Comment by camohub** [comment]
Can not install dev-master
![Screenshot (46)](https://user-images.githubusercontent.com/8393426/124268283-99823c00-db39-11eb-8d9c-97c1ff7edde4.png)

**Comment by camohub** [comment]
Yet another error
![Screenshot (47)](https://user-images.githubusercontent.com/8393426/124269135-c7b44b80-db3a-11eb-9f39-6225eb6b62eb.png)
