### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by 1cookie** [elasticquent/Elasticquent#231]
hi
I've checked and double checked my config. I'm using Laravel as my framework. I just cant get this to work?

https://stackoverflow.com/questions/65269147/no-alive-nodes-found-in-your-cluster-laravel-docker

What am i doing wrong?

**Comment by nphuy** [comment]
Check that your elasticsearch server is running.

**Comment by nphuy** [comment]
> hi
> I've checked and double checked my config. I'm using Laravel as my framework. I just cant get this to work?
> 
> https://stackoverflow.com/questions/65269147/no-alive-nodes-found-in-your-cluster-laravel-docker
> 
> What am i doing wrong?

Check that your elasticsearch server is running.

**Comment by Abdullah-Hejazi** [comment]
Check this answer, hope it helps:

https://stackoverflow.com/questions/65269147/no-alive-nodes-found-in-your-cluster-laravel-docker/65391187#65391187

**Comment by 1cookie** [comment]
Thanks Abdullah

**Comment by amitleuva1987** [comment]
@1cookie , can you please share the solution if get the solution? 

I am facing the same issue
