### ISSUE TITLE
Laravel 5.1.* Update Problem

### ISSUE THREAD

**Issue by iMestav** [elasticquent/Elasticquent#27]
Hi everybody,

I'am using laravel 5.1.*. I was using Elasticquent in my project to this day.
But in today I run "composer update" and got this error. 

Please Help Me. 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.26
    - Conclusion: don't install laravel/framework v5.1.25
    - Conclusion: don't install laravel/framework v5.1.24
    - Conclusion: don't install laravel/framework v5.1.23
    - Conclusion: don't install laravel/framework v5.1.22
    - Conclusion: don't install laravel/framework v5.1.21
    - Conclusion: don't install laravel/framework v5.1.20
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Installation request for elasticquent/elasticquent 1.0.5 -> satisfiable by elasticquent/elasticquent[v1.0.5].
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - elasticquent/elasticquent v1.0.5 requires illuminate/config ~4.2|~5.2 -> satisfiable by illuminate/config[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v5.2.0, v5.2.6, v5.2.7].
    - don't install illuminate/config v4.2.1|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.12|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.16|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.17|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.2|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.3|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.4|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.5|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.7|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.8|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.9|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.0|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.7|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].

**Comment by timgws** [comment]
Thanks for reporting this. I will fix it as soon as I get to my desk!
		
        
		
		 ---- On Thu, 28 Jan 2016 02:17:56 +1100  notifications@github.com  wrote ----Hi everybody,
I'am using laravel 5.1.*. I was using Elasticquent in my project to this day.
But in today I run "composer update" and got this error. 
Please Help Me. 
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Conclusion: remove laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.26
    - Conclusion: don't install laravel/framework v5.1.25
    - Conclusion: don't install laravel/framework v5.1.24
    - Conclusion: don't install laravel/framework v5.1.23
    - Conclusion: don't install laravel/framework v5.1.22
    - Conclusion: don't install laravel/framework v5.1.21
    - Conclusion: don't install laravel/framework v5.1.20
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Installation request for elasticquent/elasticquent 1.0.5 -> satisfiable by elasticquent/elasticquent[v1.0.5].
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - elasticquent/elasticquent v1.0.5 requires illuminate/config ~4.2|~5.2 -> satisfiable by illuminate/config[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v5.2.0, v5.2.6, v5.2.7].
    - don't install illuminate/config v4.2.1|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.12|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.16|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.17|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.2|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.3|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.4|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.5|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.7|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.8|don't install laravel/framework v5.1.0
    - don't install illuminate/config v4.2.9|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.0|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/config v5.2.7|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].

**Comment by timgws** [comment]
Or not, as it turns out... GitHub was down!

I am currently testing this now, but it should be good to go!
