### ISSUE TITLE
how to do partial search of strings

### ISSUE THREAD

**Issue by zosimanoz** [elasticquent/Elasticquent#28]
only full text match is supported. the partial match is giving empty result. How to do partial search??

**Comment by petercoles** [comment]
Elasticsearch supports a number of different types of partial match: prefix, wildcard, regexp, ngrams and two different types of search-as-type query, so how you would do a partial search would depend on which type you wanted to do.

As an example though, here's a simple example of a wildcard search that word for me:
```php
$results = Product::searchByQuery([
        "wildcard" => ['_all' => "r*do?"]
]);
```

One little gotcha - when doing this sort of wildcard search you need to cast your search string to lowercase, as that's the way that Elasticsearch indexes your text. So the example above would return products containing the text "Random" in any of the indexed fields, but "R*do?m" would return nothing.
