### ISSUE TITLE
Enable the use of Elasticquent without underlying SQL DB data.

### ISSUE THREAD

**Issue by absynthe** [elasticquent/Elasticquent#31]
Hi there,

I'm trying to use Elasticsearch as a NoSQL database and the only database for my application. I thought I could use Elasticquent for that, but there's no way of using Elasticquent in stand-alone mode so to speak, without the models being backed up by actual SQL data. Is there any chance you are going to allow that in the future ?

Right now I'm writing custom methods to go around that, but I think it would be pretty simple to enable this by just disabling some checks. For example in addToIndex, take out the exists check or combine it with another condition:

 ```
 public function addToIndex()
    {
        if (!$this->exists) {
            throw new Exception('Document does not exist.');
        }
```

**Comment by timgws** [comment]
`Elasticquent` is designed to be used as an index of existing data inside Eloquent models. This means that the data needs to be stored in a backend that Eloquent supports (such as MySQL, MSSQL etc).

You can not use this as a drop in replacement for a backend in Laravel's Query Builder.

I am not sure if I am going to support this use case going forward, as I personally don't want to use Elasticsearch as my single source of truth.

Elasticsearch has too many core issues that does not allow me to have full faith that data I give to Elasticsearch will remain there (have a look at https://www.elastic.co/guide/en/elasticsearch/resiliency/current/index.html and search for some of the `ONGOING` issues... some of them sound quite scary!)

**Comment by absynthe** [comment]
Thank you for the insight. I agree with you on the resilience issues. I will probably go with MongoDB for now.
