### ISSUE TITLE
reindex

### ISSUE THREAD

**Issue by mariavilaro** [elasticquent/Elasticquent#37]
I'm a newbie both with elasticsearch and laravel so it's possible that I'm getting this wrong:
When reindexing, it deletes the items that I have NOW in my source table, and then add them again, so if I deleted an item, it's not deleted from elasticsearch. Shouldn't reindex remove the non existent items?

**Comment by timgws** [comment]
A reindex _should not_ delete items that are not in your database. Rather, when your application is deleting data from the database, you should request that it is also removed from Elasticsearch.

By definition, `reindex` should get all the data that is currently in your model, and it should index them. If reindex also deleted data that was in your database, it would be doing more then you asked it to do!

If there is data missing from your source (say a MySQL database) that is in Elasticsearch, reindex should not delete it.

You can use [Laravel Events](https://laravel.com/docs/5.1/eloquent#events) on Eloquent to ensure that when data is being deleted (or has been deleted... there are two events that you can listen for) that it is then also removed from Elasticsearch.

This is a better way in my opinion then deleting data that is not in the database when performing a reindex.

What do you think @mariavilaro?

**Comment by mariavilaro** [comment]
I think that you are ok. Reindex should'nt delete data. But shouldn't also be a way to delete al documents in a type or in a index without deleting the index itself?

**Comment by timgws** [comment]
That exists already.

You want to call [`->deleteFromIndex()`](https://github.com/elasticquent/Elasticquent/blob/0234890532ab50fd1944c476b9e9929173753879/src/ElasticquentCollectionTrait.php#L43-L65) on the model, then run reindex() again.

**Comment by timgws** [comment]
Actually, that won't work, because that will still only look at the data that is in the model. Sorry.

Call [`->deleteIndex()`](https://github.com/elasticquent/Elasticquent/blob/0234890532ab50fd1944c476b9e9929173753879/src/ElasticquentTrait.php#L549-L565) and then [`->addAllToIndex()`](https://github.com/elasticquent/Elasticquent/blob/0234890532ab50fd1944c476b9e9929173753879/src/ElasticquentTrait.php#L194-L208)

**Comment by timgws** [comment]
Call [`->deleteIndex()`](https://github.com/elasticquent/Elasticquent/blob/0234890532ab50fd1944c476b9e9929173753879/src/ElasticquentTrait.php#L549-L565), `->createIndex()` and then [`->addAllToIndex()`](https://github.com/elasticquent/Elasticquent/blob/0234890532ab50fd1944c476b9e9929173753879/src/ElasticquentTrait.php#L194-L208)

There is a way to delete data in Elasticsearch, but it has a number of issues. The first one is
> deleting data from the index silently forces a refresh which can quickly cause OutOfMemoryError during concurrent indexing. [[1]](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-delete-by-query.html)

The second issue is that
> it will delete mappings [[2]](http://stackoverflow.com/a/30785175/2143004)
(although, they will come back when the first document is put back)

The documentation recommends using the Elasticsearch [scrolling and bulk deleting](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-scroll.html), which I may get around to implementing one day (although, tbh, at the moment I don't need this functionality)

**Comment by mariavilaro** [comment]
Yes, probably I only need this functionality because I'm testing the system and learning the platforms, it's probably not of much use in a production system. Thank you!
