### ISSUE TITLE
Hydrating models from results

### ISSUE THREAD

**Issue by onbjerg** [elasticquent/Elasticquent#46]
Hi!

Is it possible to retrieve a collection of models with all of the database info, as opposed to just the documents returned by ElasticSearch?

If not, maybe we could add a ``hydrate`` method to the results collection?

**Comment by onbjerg** [comment]
Here's an example of manual hydration from search results (with some extra code because of #47):

```php
$books = Book::hydrate(
    (new Collection(Book::search('moby dick')))->pluck('id')->toArray()
);
```

If #47 was resolved, the code would be a bit cleaner:

```php
$books = Book::hydrate(
    Book::search('moby dick')->pluck('id')->toArray()
);
```

If we implemented some sort of hydration method, we could probably just do

```php
$books = Book::search('moby dick')->hydrate();

// or

$books = Book::search('moby dick', $hydrate = true);
```

**Comment by timgws** [comment]
Done.
