### ISSUE TITLE
Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.

### ISSUE THREAD

**Issue by sfolador** [elasticquent/Elasticquent#53]
Hi, 
I tried a bulk add as shown is your readme but instead I get this error:

`
"error" => array:2 [
          "type" => "mapper_parsing_exception"
          "reason" => "Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."
        ]
`

The model I'm trying to add is just a test model, and it's something like:

`
        "title" => "MRdTvVwMTGSl"
        "updated_at" => "2016-04-04 15:58:29"
        "created_at" => "2016-04-04 15:58:29"
        "_id" => "57028f25633db3473d0041c8"
`

I have ElasticSearch 2.1 and it's under Mac OSX 10.11.3
Any advice?

**Comment by timgws** [comment]
Where is the data coming from?

Can you change the `_id` field to something else? (such as `id` without the underscore infront)?

**Comment by sfolador** [comment]
Hi, 
the data is coming from a Mongo DB instance. Don't worry, I've already subclassed the ElasticquentTrait and "converted" the "_id" field to "id" .Now it works. Thanks.

**Comment by coniolabs** [comment]
Hi, @sfolador , would you please show what you change in ElasticquentTrait ?
Thanks

**Comment by deamnguyen** [comment]
@ronytampubolon, you can try this code to remove _id field

`filter {`
`  mutate {`
`    copy => { "id" => "[@metadata][_id]"}`
`    remove_field => ["_id"]`
`  }`
`}`

`output {`
`  elasticsearch {`
 `     index => "rdbms_sync_idx" // your index`
 `     document_id => "%{[@metadata][_id]}"`
 ` }
`}`

**Comment by prabhat2k15** [comment]
where should i put this code...i am using Laravel mongo stack. Please help @deamnguyen

**Comment by deamnguyen** [comment]
> where should i put this code...i am using Laravel mongo stack. Please help @deamnguyen

that code used to Logstash. I use Logstash for sync data from MongoDB to Elasticsearch. So, `where should i put this code` you can put this code where <logstash>/config/my-config.conf
