### ISSUE TITLE
How can I set the analyzer

### ISSUE THREAD

**Issue by neowill2013** [elasticquent/Elasticquent#57]
I want to use stemming. But don't find any way to add setting using elasticquent

**Comment by chuangbo** [comment]
Pull request #56 Added support for custom analyzer but havn't merge yet. You can try my fork https://github.com/chuangbo/Elasticquent or waiting for merging.

**Comment by neowill2013** [comment]
@chuangbo Thanks

**Comment by neowill2013** [comment]
@timgws Please merge this
