### ISSUE TITLE
Yesterdays merge created this error for me.

### ISSUE THREAD

**Issue by Thedigit** [elasticquent/Elasticquent#61]
Everything was working fine before this morning.

**This commit:**
https://github.com/elasticquent/Elasticquent/pull/58/commits/b53834ffc037a4ff10a7a0cb2dd2cfdda9add3ef

**Error:**
Missing argument 1 for Illuminate\Database\Eloquent\Model::updated(), called in /vendor/elasticquent/elasticquent/src/ElasticquentTrait.php on line 693 and defined

**Little more data:**

- **DB** : (Mongo) using "jenssegers/mongodb": "3.0.*" plugin
- **Elasticquent Version** : "elasticquent/elasticquent": "dev-master"
- **Laravel Version** : "laravel/framework": "5.2.*"

I will see if i can modify the commit to work for my set up and commit my changes for a possible fix. for production I will just going to revert the commit on my side for now to get the app back up but i thought i should share for future development. 

Edit: So I believe i have figured out the issue i am having. jenssegers/mongodb puts a modifier on the model obj. which changes the "updated_at" "created_at" to mongo date type obj.

**Comment by Thedigit** [comment]
I have found a solution and made the modification : https://github.com/elasticquent/Elasticquent/pull/62 .

Hope this doesn't affect what was originally intended @neowill2013, @chuangbo, @timgws

**Comment by chuangbo** [comment]
@Thedigit Can you post a gist of the model?

I just quick look through jenssegers/mongodb, it seems all the relation methods like `belongsTo` are inherited from laraval Relation. So I don't understand why `instanceof` failed.

**Comment by Thedigit** [comment]
@chuangbo I saw that as well. I was trying to figure out the same.

The Model is very basic and has no relations implied, what i am assuming is that the plugin jenssegers/mongodb puts a modifier relation on the base "Illuminate\Database\Eloquent\Model" to transform the "updated_at", "created_at" to Mongo date/time Objects. i plan to debug this a bit more but i figured i mention it just incase any one else has similar issues.

**Comment by timgws** [comment]
@chuangbo @Thedigit could you please test the last two commits and let me know if this has fixed your problems?

**Comment by Thedigit** [comment]
@timgws I just pulled and it seemed to work perfectly now =). 
Sorry about the sloppy tabbing. 

Thanks again!
