### ISSUE TITLE
Add fuzzyness?

### ISSUE THREAD

**Issue by huglester** [elasticquent/Elasticquent#68]
Hello,

what would be the best way to search with some fuzzyness in mind?
Because now, for example I have: "Blackman" - If i search of it, it find. But if I search for "Blackma" (ommiting last letter) - I won't be able to find it and elastic returns - 0 Hits.

Thank you

**Comment by nonotest** [comment]
hello,

you have multiple way of dealing with that.
I think what suits best your example is something like this:

````
// first create a custom index with ngrams
// [..] skipping the other config settings

       $index['body']['settings']['analysis']['filter']['ngram_filter'] = [
            'type' => 'nGram',
            'min_gram' => 2,
            'max_gram'=> 20
        ];

        $index['body']['settings']['analysis']['analyzer']['ngram_analyzer'] = [
            'type' => 'custom',
            'tokenizer' => 'standard',
            'filter' => [
                'lowercase',
                'ngram_filter'
            ]
        ];
        $client->indices()->create($index);

       // your query...
       $query = [
                    'body' => [
                        'query' =>  [
                            'match_phrase' => [
                                'name' => 'Blackma'
                            ]
                        ]
                    ]
      ];

      MyModel::complexSearch($query);


     ````



For true fuzziness (eg in your case blackmna...) you would need to use this:

````
                $query['fuzziness'] = 'AUTO';
````

let me know if this helps.

**Comment by huglester** [comment]
Hello,

well I tried different scenarios, but still no luck :/

So I have this index, as you posted?
```php
$index['index'] = 'ads';
        $index['body']['settings']['analysis']['filter']['ngram_filter'] = [
            'type' => 'nGram',
            'min_gram' => 1,
            'max_gram'=> 20
        ];
        $index['body']['settings']['analysis']['analyzer']['ngram_analyzer'] = [
            'type' => 'custom',
            'tokenizer' => 'standard',
            'filter' => [
                'lowercase',
                'ngram_filter'
            ]
        ];

        $client = (new Ad)->getElasticSearchClient();
        $client->indices()->delete(['index' => 'ads']);
        $client->indices()->create($index);
```

Later I push items to the index.
And it generally works as earlier :/

I found out one more thing:

If index have: "komsomolec"

So I search for example "komsomole" - I have 0 results.

But If I search for "komsomole*" - I can find it! But I can find it only via default API, like this:
http://docker.app:9200/_search?pretty=true&q=komsomole*

Using for example Ad::search() this does return zero results.

But anyway I also would like to allow users to make 'mistakes'. so If I make small typos, I still get the results.

I will try now to docs for this:  $query[...]['fuzziness'] = 'AUTO';

Will post the results later :)

**Comment by chuangbo** [comment]
I suggest to customize the search query in [Sense](https://www.elastic.co/guide/en/sense/current/sense-ui.html) (or other similar UIs) first, then back to elasticquent and implement the logic in PHP.

**Comment by huglester** [comment]
Interesting. Thank you. I will look into sense.
