### ISSUE TITLE
Having trouble searching for partial words

### ISSUE THREAD

**Issue by brockwddb** [elasticquent/Elasticquent#9]
Hello -

I'm new to this, so I'm not having the easiest time using the package. I managed to get it running in the application, but I'm a little confused on how to do this.

I'm trying to search a field that has values like `00600005044` for `600005044` or `5044` and I'm receiving 0 results. If I search for the whole value (with leading zeros), I get the intended result back.

I have tried messing around with the mapping properties.
````php 
protected $mappingProperties = array(
   'testField' => array(
        'type' => 'string',
        'analyzer' => 'standard'
    )
);
````
and 
````php 
protected $mappingProperties = array(
   'testField' => array(
        'type' => 'string',
        'analyzer' => 'wildcard'
    )
);
````
and
````php 
protected $mappingProperties = array(
   'testField' => array(
        'type' => 'integer',
        'analyzer' => 'standard'
    )
);
````
It seems like everything I try gives me the same results. Also, I've noticed that after changing those and running `rebuildMappings()` it always returns the same analyzer.

Any help would be greatly appreciated.

**Comment by timgws** [comment]
Hey @brockwddb,

Have you tried performing a wildcard query as per [the documentation on the subject (wildcard and regexp Queries)](https://www.elastic.co/guide/en/elasticsearch/guide/current/_wildcard_and_regexp_queries.html)


    GET /my_index/address/_search
    {
        "query": {
            "wildcard": {
                "postcode": "W?F*HW" 
            }
        }
    }

**Comment by brockwddb** [comment]
I have been trying to understand that documentation for a few days now, to no avail. Where exactly does that query string go in relation to the laravel package? 

Is that the parameter you pass to the search function of the model?

**Comment by timgws** [comment]
@brockwddb check out this: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html

    {
        "query": {
            "wildcard": {
                "serial": "*5044" 
            }
        }
    }

To run this query (in a manual way) using Elasticquent, do the following:

```php
$model = new Books();

$params = $model->getBasicEsParams();
$params['body'] = ['query' => ['wildcard' => ['serial' => "*5044"] ] ];

$results = $model->complexSearch($params);
```

**Comment by brockwddb** [comment]
That appears to have fixed my issue. Thank you very much for your help!

**Comment by MasoumehEbhami** [comment]
Hey @timgws 
I have one problem with searching in multi fields ,
This code work for me but i want search in multi filed like name and family:

`$model = new Person();

$params = $model->getBasicEsParams();
$params['body'] = ['query' => ['wildcard' => ['name' => "*mas"] ] ];

$results = $model->complexSearch($params);`

can you help me for optimize this query for searching in name and family fields,
Thanks
