### ISSUE TITLE
multiple match question

### ISSUE THREAD

**Issue by morenDev** [elasticquent/Elasticquent#90]
```json

{
    "bool" : {
        "must" : [{
            "match" : {
                "user_id" : "1"
            },
            "match" : {
                "name" : "John"
            }
        }]
    }
}
```

How can i handle such requests? I mean a several match in it.

**Comment by flyingcoder** [comment]
How you handle this problem?

**Comment by morenDev** [comment]
by using filter

**Comment by Fabiencdp** [comment]
Can you explain a little more or give an example ? I'm stuck on the same issue.
Thanks !

**Comment by morenDev** [comment]
@Fabiencdp Are you still on it?

**Comment by Fabiencdp** [comment]
Sorry for the delay. 

I finally found the answer, i'm new to ES, but i think i'm right doing it that way : 

`array:1 [
  "body" => array:2 [
    "query" => array:1 [
      "bool" => array:1 [
        "must" => array:1 [
          "geo_bounding_box" => array:1 [
            "locations" => array:2 [
              "top_left" => array:2 [
                "lat" => 44.982380962151
                "lon" => -0.73239649316406
              ]
              "bottom_right" => array:2 [
                "lat" => 44.690231781258
                "lon" => -0.43988550683594
              ]
            ]
          ]
        ]
      ]
    ]
    "filter" => array:1 [
      "bool" => array:1 [
        "must" => array:2 [
          0 => array:1 [
            "range" => array:1 [
              "prices" => array:2 [
                "gte" => "10"
                "lte" => "200"
              ]
            ]
          ]
          1 => array:1 [
            "range" => array:1 [
              "capacity" => array:1 [
                "gte" => "5"
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]`

**Comment by morenDev** [comment]
I've drop this package and working with Elastica now, which is far more flexible. You should try it, It has a nice query builder )
